= HTTP Signature

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-http-signature/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-http-signature/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^| -

|===

== Description

HTTP Signature is a kind of authentication method which is adding a new level of security. By using this policy, the
consumer is enforced to send a _signature_ which is used to identify the request temporarily and ensure that the
request is really coming from the requesting consumer, using a secret key.

NOTE: Current version of the policy does not support *Digest* header.

== Configuration

|===
|Property |Required |Description |Default |Example

.^|scheme
^.^|X
|Signature Scheme (authentication scheme or signature header)
^.^| authentication
^.^| -

.^|secret
^.^|X
|The secret key used to generate and verify the signature (supports EL).
^.^| -
^.^| passphrase

.^|algorithms
^.^|-
|A list of supported HMAC digest algorithms.
^.^| -
^.^| -

.^|enforceHeaders
^.^| -
|List of headers the consumer must at least use for HTTP signature creation.
^.^| -
^.^| -

.^|clockSkew
^.^|-
|Clock Skew in seconds to prevent replay attacks.
^.^| 30
^.^| -

|===


[source, json]
.HTTP Signature Policy example:
----
{
  "http-signature": {
	"scheme":"AUTHORIZATION",
	"clockSkew":30,
	"secret":"my-passphrase",
	"algorithms":["HMAC_SHA256"],
	"enforceHeaders":["Date","Host"]
  }
}
----

== Http Status Code

|===
|Code |Message

.^| ```401```
| In case of:

* Missing or signature

* Request does not contain headers part of the signature

* Enforce HTTP headers not part of the signature
|===

== Errors

If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys send by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|HTTP_SIGNATURE_INVALID_SIGNATURE
^.^|-

|===
